### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by michaelck** [CityOfPhiladelphia/trashday#3]
## Errors
- [x] Document language missing
- [x] Site logo image missing alternative text
- [x] Enter address form field missing label
- [x] Empty`button` in address lookup area (should have screen readable text at minimum)
- [x] Linked `h1` registering as empty

**Comment by karissademi** [comment]
Thanks, @michaelck!

**Comment by michaelck** [comment]
Jekyll build failed on this, opening until the build passes
